---
- name: install redis deps
  yum: name={{item}} state=present
  with_items:
  - make
  - gcc
  - wget
  tags: redis

- name: download redis source
  shell: wget -O - http://download.redis.io/releases/redis-{{app.redis.version}}.tar.gz | tar -xz -C /tmp creates=/tmp/redis-{{app.redis.version}}
  tags: redis

- name: install redis
  shell: make chdir=/tmp/redis-{{app.redis.version}} creates=/tmp/redis-{{app.redis.version}}/src/redis-server
  tags: redis

- name: move compiled redis binaries
  shell: cp {{item}} /usr/local/bin chdir=/tmp/redis-{{app.redis.version}}/src creates=/usr/local/bin/{{item}}
  with_items:
  - redis-cli
  - redis-server
  - redis-benchmark
  tags: redis

- name: configure redis-server
  template: src=redis.conf.j2 dest=/etc/redis.conf
  notify: restart redis
  tags: redis

- name: make redis a service
  template: src=redis_init_script.j2 dest=/etc/init.d/redis mode=755
  tags: redis

- name: run redis
  shell: /etc/init.d/redis start creates=/var/run/redis.pid
  tags: redis